CREATE TABLE IF NOT EXISTS employes(
    id integer PRIMARY KEY,
    fullname text NOT NULL CHECK (fullname <> ''),
    idjefe integer,
    cargo text NOT NULL,
    isboss boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS boos(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fullname text NOT NULL CHECK (fullname <> ''),

);

INSERT INTO employes(id, fullname, cargo, isboss, idjefe)
    VALUES(1001,'julian alvarez', 'developer', true, null);
INSERT INTO employes(id, fullname, cargo, isboss, idjefe)
    VALUES(1002,'alvaro galindo', 'product owner', true, null);
INSERT INTO employes(id, fullname, cargo, isboss, idjefe)
    VALUES(1003,'juan monsalve', 'developer', false, 1001);
SELECT * FROM employes;
